[test]
# Test configuration for Bun
timeout = "10s"
# Temporarily ignore Jest-dependent files during migration
ignore = [
  "tests/integration/api.integration.test.js",
  "tests/unit/notification.test.js", 
  "tests/unit/parser.test.js",
  "tests/unit/fetcher.test.js",
  "tests/unit/crawlService.test.js",
  "tests/unit/crawler.test.js",
  "tests/unit/multiStationCrawler.test.js"
]