version: '3.8'

services:
  api:
    build:
      context: ../../
      dockerfile: apps/crawler/Dockerfile
    container_name: crawler-api-prod
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env.production
    environment:
      - TZ=Asia/Taipei
    volumes:
      - debug_html:/app/debug-html
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  debug_html:
    driver: local