"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./assets/main.css");
var vue_1 = require("vue");
var pinia_1 = require("pinia");
var element_plus_1 = require("element-plus");
require("element-plus/dist/index.css");
var App_vue_1 = require("./App.vue");
var router_1 = require("./router");
var app = (0, vue_1.createApp)(App_vue_1.default);
var pinia = (0, pinia_1.createPinia)();
app.use(pinia);
app.use(router_1.default);
app.use(element_plus_1.default);
app.mount('#app');
